language: node_js
matrix:
  fast_finish: true
  allow_failures:
  - node_js: '5'
node_js:
- '0.12'
- '0.10'
- '4'
- '5'
services:
- couchdb
env:
  global:
  - NODE_ENV=test
  - NAME=appname
  - TOKEN=apptoken
before_install:
- npm install -g npm@latest-2
before_script:
- npm run travis-before
deploy:
  provider: npm
  skip_cleanup: true
  on:
    tags: true
    node: '4'
  api_key:
    secure: TxW9CktbFR6xUz/OLu4dCbAJICoYU4M2nMf7F9crO5vFdwouI86p7CVQ8o6ug1G1jxWjECYpilDmhsHOEWFaBbKrM0CJQsGfFKhKiHDLrf7O6lhhBKZHrx67WDHgQ1LDjo6Pd2fuFsdmAdEm890MavA1vvnqS4ycqECOuBcHY8s=
